/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=dev --include-runtime=false --strict-vars=false env.d.ts` (hash: af749e4db8d2e63a94559a810ad6db46)
interface __BaseEnv_Env {
	OAUTH_ISSUER: string;
	OAUTH_AUDIENCE: string;
	STATS: DurableObjectNamespace<import("./src/index").TourStats>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "TourStats";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OAUTH_ISSUER" | "OAUTH_AUDIENCE">> {}
}
