/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=dev --include-runtime=false --strict-vars=false env.d.ts` (hash: 11c74bfd39a912fe4cab47205cd9f8f3)
interface __BaseEnv_Env {
	OAUTH_ISSUER: string;
	OAUTH_AUDIENCE: string;
	R2_ACCOUNT_ID: string;
	R2_BUCKET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OAUTH_ISSUER" | "OAUTH_AUDIENCE" | "R2_ACCOUNT_ID" | "R2_BUCKET">> {}
}
