// Builds styles/icons.css for the subset fonts. Pure and import-free: the generator
// (scripts/gen-icons.mjs) loads it with plain Node, and icons.test.ts checks the
// committed file against it.

/** Map every `.fa-<name>{--fa:"\xxxx"}` rule in Font Awesome's CSS to its codepoint. */
export function faCodepoints(css: string): Map<string, number> {
  const map = new Map<string, number>();
  for (const m of css.matchAll(/([^{}]+)\{--fa:"\\([0-9a-f]+)"/g)) {
    const code = parseInt(m[2] as string, 16);
    for (const sel of (m[1] as string).split(',')) {
      const name = /^\s*\.fa-([a-z0-9-]+)\s*$/.exec(sel)?.[1];
      if (name) map.set(name, code);
    }
  }
  return map;
}

/** The codepoints of `names`; throws on a name Font Awesome doesn't have. */
export function codepointsFor(names: readonly string[], map: Map<string, number>): number[] {
  return names.map((name) => {
    const code = map.get(name);
    if (code === undefined) throw new Error(`no Font Awesome icon "${name}"`);
    return code;
  });
}

const hex = (code: number) => code.toString(16);
const rules = (names: readonly string[], map: Map<string, number>) => {
  const codes = codepointsFor(names, map);
  return names.flatMap((n, i) => [`.fa-${n} {`, `  --fa: '\\${hex(codes[i] as number)}';`, '}']);
};

export interface IconsCssInput {
  solid: readonly string[];
  brands: readonly string[];
  /** Codepoints by name, from faCodepoints over Font Awesome's CSS. */
  codepoints: Map<string, number>;
  /** Codepoint shown for a solid name outside the subset. */
  fallback: string;
  /** Font Awesome version the glyphs come from (for the licence banner). */
  version: string;
}

/** The whole icons.css: licence banner, @font-face, base classes and one rule per icon. */
export function iconsCss({ solid, brands, codepoints, fallback, version }: IconsCssInput): string {
  const fallbackCode = hex(codepointsFor([fallback], codepoints)[0] as number);
  return [
    '/* GENERATED by scripts/gen-icons.mjs from src/icons/names.ts. Do not edit. */',
    `/* Font Awesome Free ${version} subset. https://fontawesome.com/license/free`,
    ' * Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License. Copyright 2024 Fonticons, Inc. */',
    '@font-face {',
    "  font-family: 'Font Awesome 6 Free';",
    '  font-style: normal;',
    '  font-weight: 900;',
    // PUA glyphs: a fallback font would draw tofu, so wait for the (small) subset.
    '  font-display: block;',
    "  src: url('./fa/fa-solid-subset.woff2') format('woff2');",
    '}',
    '@font-face {',
    "  font-family: 'Font Awesome 6 Brands';",
    '  font-style: normal;',
    '  font-weight: 400;',
    '  font-display: block;',
    "  src: url('./fa/fa-brands-subset.woff2') format('woff2');",
    '}',
    '.fa-solid,',
    '.fa-brands {',
    '  -moz-osx-font-smoothing: grayscale;',
    '  -webkit-font-smoothing: antialiased;',
    '  display: var(--fa-display, inline-block);',
    '  font-style: normal;',
    '  font-variant: normal;',
    '  line-height: 1;',
    '  text-rendering: auto;',
    '}',
    '.fa-solid {',
    "  font-family: 'Font Awesome 6 Free';",
    '  font-weight: 900;',
    '}',
    '.fa-brands {',
    "  font-family: 'Font Awesome 6 Brands';",
    '  font-weight: 400;',
    '}',
    `/* A solid name outside the subset (stored tours accept any name) shows ${fallback}. */`,
    '.fa-solid::before {',
    `  content: var(--fa, '\\${fallbackCode}');`,
    '}',
    '.fa-brands::before {',
    '  content: var(--fa);',
    '}',
    '.fa-spin {',
    '  animation-name: fa-spin;',
    '  animation-delay: var(--fa-animation-delay, 0s);',
    '  animation-direction: var(--fa-animation-direction, normal);',
    '  animation-duration: var(--fa-animation-duration, 2s);',
    '  animation-iteration-count: var(--fa-animation-iteration-count, infinite);',
    '  animation-timing-function: var(--fa-animation-timing, linear);',
    '}',
    '@keyframes fa-spin {',
    '  0% {',
    '    transform: rotate(0deg);',
    '  }',
    '  to {',
    '    transform: rotate(1turn);',
    '  }',
    '}',
    '@media (prefers-reduced-motion: reduce) {',
    '  .fa-spin {',
    '    animation-delay: -1ms;',
    '    animation-duration: 1ms;',
    '    animation-iteration-count: 1;',
    '  }',
    '}',
    '/* solid */',
    ...rules(solid, codepoints),
    '/* brands */',
    ...rules(brands, codepoints),
    '',
  ].join('\n');
}
