// The Font Awesome icons panote ships. styles/icons.css and the subset fonts in
// styles/fa/ are generated from these lists (`pnpm --filter @internal/ui gen:icons`),
// so an icon outside them renders blank (or as FALLBACK_ICON for solid).
// Keep this file free of imports: the generator loads it with plain Node.

/** Solid icons offered by the editor's point icon picker. */
export const POINT_ICONS = [
  'info',
  'circle-info',
  'star',
  'heart',
  'camera',
  'image',
  'video',
  'music',
  'microphone',
  'book',
  'book-open',
  'landmark',
  'building',
  'church',
  'mosque',
  'synagogue',
  'monument',
  'archway',
  'house',
  'door-open',
  'stairs',
  'elevator',
  'bed',
  'bath',
  'couch',
  'chair',
  'utensils',
  'mug-hot',
  'wine-glass',
  'beer-mug-empty',
  'store',
  'cart-shopping',
  'tree',
  'leaf',
  'seedling',
  'mountain',
  'water',
  'sun',
  'moon',
  'cloud',
  'snowflake',
  'fire',
  'car',
  'bus',
  'train',
  'bicycle',
  'person-walking',
  'wheelchair',
  'square-parking',
  'restroom',
  'phone',
  'envelope',
  'location-dot',
  'map',
  'compass',
  'flag',
  'clock',
  'calendar',
  'ticket',
  'palette',
  'paintbrush',
  'masks-theater',
  'futbol',
  'person-swimming',
  'dumbbell',
  'graduation-cap',
  'lightbulb',
  'gear',
  'wrench',
  'triangle-exclamation',
  'question',
  'link',
  'arrow-up',
  'eye',
] as const;

/** Solid icons the apps and viewer chrome render by class name (`fa-solid fa-<name>`). */
export const UI_ICONS = [
  'angles-up',
  'arrow-left',
  'arrow-right-from-bracket',
  'arrow-up',
  'arrow-up-from-bracket',
  'ban',
  'building',
  'calendar-day',
  'camera',
  'chart-line',
  'check',
  'chevron-left',
  'chevron-right',
  'circle-check',
  'circle-exclamation',
  'circle-info',
  'circle-notch',
  'clone',
  'cloud-arrow-up',
  'code',
  'code-merge',
  'compass',
  'compress',
  'crosshairs',
  'diagram-project',
  'diamond-turn-right',
  'exclamation',
  'expand',
  'eye',
  'eye-slash',
  'feather',
  'flag',
  'globe',
  'graduation-cap',
  'heart',
  'hourglass-half',
  'house',
  'image',
  'images',
  'infinity',
  'landmark',
  'layer-group',
  'link',
  'location-arrow',
  'location-dot',
  'lock',
  'lock-open',
  'magnifying-glass-plus',
  'map',
  'minus',
  'mobile-screen',
  'panorama',
  'pen',
  'pencil',
  'plane',
  'plus',
  'rotate',
  'rotate-right',
  'server',
  'share-nodes',
  'shield-halved',
  'sliders',
  'spinner',
  'star',
  'table-cells-large',
  'trash',
  'trash-can',
  'triangle-exclamation',
  'xmark',
] as const;

/** Brand icons (`fa-brands fa-<name>`): sign-in connections and share targets. */
export const BRAND_ICONS = [
  'apple',
  'facebook',
  'facebook-f',
  'google',
  'linkedin-in',
  'whatsapp',
  'x-twitter',
] as const;

/** Every solid icon in the subset font, sorted. */
export const SOLID_ICONS: readonly string[] = [...new Set([...POINT_ICONS, ...UI_ICONS])].sort();

/** Point icon used when none is set. */
export const DEFAULT_POINT_ICON = 'info';

/** Shown for a stored icon name that isn't in the subset (contracts accept any FA name). */
export const FALLBACK_ICON = 'circle-info';

const solid = new Set(SOLID_ICONS);

/** The solid icon to render for a point's stored `icon`. */
export function pointIcon(name: string | null | undefined): string {
  if (!name) return DEFAULT_POINT_ICON;
  return solid.has(name) ? name : FALLBACK_ICON;
}
