/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=dev --env-file=/dev/null --include-runtime=false --strict-vars=false worker/env.d.ts` (hash: 3ac7d85b414948b02760a902ef2d1a45)
interface __BaseEnv_Env {
	BUCKET: R2Bucket;
	INDEXABLE: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
