/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=dev --env-file=/dev/null --include-runtime=false --strict-vars=false worker/env.d.ts` (hash: c0f70f4373bcdee0d1690b746c63df09)
interface __BaseEnv_Env {
	BUCKET: R2Bucket;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
