/**
 * Paths no ESLint run in this monorepo should ever look at.
 *
 * Kept separate from the config bodies so that both the base and the react
 * variant share one definition, and so a consumer can extend rather than
 * replace it.
 */
export const commonIgnores: string[] = [
  '**/dist/**',
  '**/build/**',
  '**/coverage/**',
  '**/node_modules/**',
  '**/.turbo/**',
  '**/.wrangler/**',
  '**/*.tsbuildinfo',
  // Generated by `wrangler types`. Its leading `/* eslint-disable */` does not
  // stop it being linted - with zero actual violations in the generated
  // output, that directive is itself flagged as an unused eslint-disable
  // (`reportUnusedDisableDirectives` is on by default), which then fails
  // `--max-warnings 0`. Ignoring the file outright is the only fix; the
  // leading comment alone is not enough.
  '**/worker-configuration.d.ts',
  // Same generator, same reason, for the per-service Env-only half split out
  // of worker-configuration.d.ts (`wrangler types --include-runtime=false`).
  // Scoped to each service's package root (not `**/env.d.ts`) so it does not
  // also swallow hand-written `src/env.d.ts` files, which declare secret
  // bindings and are ordinary linted/formatted source.
  'services/*/env.d.ts',
];
