/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=dev --include-runtime=false --strict-vars=false env.d.ts` (hash: b8925e6f62ec5c36ba5878913b92d349)
interface __BaseEnv_Env {
	BUCKET: R2Bucket;
	MAX_ORIGINAL_BYTES: string;
	R2_ACCOUNT_ID: string;
	R2_BUCKET: string;
	TILER: DurableObjectNamespace<import("./src/consumer").Tiler>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/consumer");
		durableNamespaces: "Tiler";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MAX_ORIGINAL_BYTES" | "R2_ACCOUNT_ID" | "R2_BUCKET">> {}
}
