/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=dev --include-runtime=false --strict-vars=false env.d.ts` (hash: e22b99ffc14b94008fc1c411c6a51b7e)
interface __BaseEnv_Env {
	BUCKET: R2Bucket;
	OAUTH_ISSUER: string;
	OAUTH_AUDIENCE: string;
	CF_ACCOUNT_ID: string;
	AE_DATASET: string;
	SLUG_ALIAS_DAYS: string;
	CDN_ZONE_ID: string;
	CDN_HOST: string;
	PUBLISHER: DurableObjectNamespace<import("./src/index").TourPublisher>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "TourPublisher";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OAUTH_ISSUER" | "OAUTH_AUDIENCE" | "CF_ACCOUNT_ID" | "AE_DATASET" | "SLUG_ALIAS_DAYS" | "CDN_ZONE_ID" | "CDN_HOST">> {}
}
