/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=dev --include-runtime=false --strict-vars=false env.d.ts` (hash: 41e4c65d27ae175cc3c52f7227013834)
interface __BaseEnv_Env {
	BUCKET: R2Bucket;
	OAUTH_ISSUER: string;
	OAUTH_AUDIENCE: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OAUTH_ISSUER" | "OAUTH_AUDIENCE">> {}
}
