import { react } from '@internal/eslint-config/react';

// worker/env.d.ts is generated by `wrangler types` (see STANDARDS.md, TypeScript).
export default [{ ignores: ['worker/env.d.ts'] }, ...react];
